### PR TITLE
Open wifi AP/STA dual mode in BoardConfig.mk

### PR DESCRIPTION
**Pull request by zhaoye1**
set WIFI_HIDL_FEATURE_DUAL_INTERFACE := true

### CODE REVIEW

**Comment by zhaoye1** [comment]
@zhaoye1
[Open wifi AP/STA dual mode in BoardConfig.mk](https://github.com/projectceladon/device-androidia/pull/1737/commits/a25510490f2310b58cb588cb6705cb94502566c7)

**Comment by zhaoye1** [comment]
@balajim001  please help me review the patch, and help me add Panda, Bharat B to review, thanks.

**Comment by zhaoye1** [comment]
@bpanda24 please help me review the patch

**Review by bpanda24 — APPROVED** [review]

**Review by maozhong1 — APPROVED** [review]

**Review by lchen43 — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Pull request merged**
