### PR TITLE
x86: config: enable i915 tripple buffer

### PR DESCRIPTION
**Pull request by vipinanand**
It enables tripple buffer for i915 drm fb driver to increase the gfx
performance.

Tracked-On: OAM-76034
Signed-off-by: Vipin Anand <vipin.anand@intel.com>
Signed-off-by: Ankit Navik <ankit.p.navik@intel.com>
Signed-off-by: Kedar J Karanje <kedar.j.karanje@intel.com>

### CODE REVIEW

**Comment by apnavik** [comment]
> Autobuild started from pull-request-changes on this PR.
> 
> FAILURE: Trigger Builds Triggered: build-cel - celadon (cel_apl) - extra, build-cel - celadon (celadon)
> 
> For more information, see: /absp/builders/celadon-autobuild/builds/278

This failure is due to 
**Conflicts          device/intel/project-celadon/0003-CELADON-Change-api-level-to-25.patch**
which is not related to this.

**Comment by harishkrupo** [comment]
It is surprising to see that a change in the fbdev emulation code is improving performance. :)
I am not exactly sure how the fbdev emulation subsystem interacts with i915 fb creation...
Ping @js0701 
Do you know how this is causing performance improvement?

**Comment by js0701** [comment]
@vipinanand what is the test cases you are using? how much improvement?
I don't think fbdev is used a lot in Andriod

**Comment by vipinanand** [comment]
Hi @js0701 
for GFXBench offscreen tests it is improved by 5% on APL-NUC and 3% on KBL-NUC device with Celadon.

**Comment by tpalli** [comment]
This is indeed a bit strange, maybe it enables/disables some toggles, would be good to understand what exactly happens as example in case there will be issues because of this.

**Comment by tpalli** [comment]
Maybe verify the testing results and make sure nothing else is run on background? (or dying and restarting all the time like bluetooth and thermal-daemon seems todo now and then)

**Comment by harishkrupo** [comment]
AFAICT from the code, drm_fbdev subsystem registers with fbcon as a backend and provides it with minimal text rendering capabilities. In order to do so, it allocates a framebuffer during startup using i915. The allocated size is controlled by the overalloc config [here](https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_fb_helper.c#L1974). The name triple buffer here refers to something different compared to the triple buffering used in userspace. The overalloc variable actually controls the height of the buffer, not the number of buffers like in a triple buffered system. This makes sense when considering text terminals, as larger the height, more content can be written before clearing the screen.

All this said, I am still not sure how this is showing improvement in your tests as this path shouldn't be used once the VT is switched to graphics mode.

**Comment by js0701** [comment]
Agree that we should make the test result reprodusible

**Comment by apnavik** [comment]
@tpalli : We have verified GFXBench (Trex-off, Manhattan-off and Carchase off) and 3DMark- Ice storm which has shown improvements. We did not see any adverse effect in any other PnP KPIs/tests.  
Could you please let us know any specific test case you want us to verify?

@js0701 : Can you please try with this patch and check if you see similar improvement with [Celadon-Android](https://01.org/projectceladon/documentation/getting_started/build-source) on KBL-NUC and APL-NUC.

**Comment by apnavik** [comment]
@tpalli @js0701 @harishkrupo :
we have also notice stark differences in the GPU frequency residencies in the higher freq range (with OVERALLOC at 300 vs OVERALLOC at 100)

**Comment by harishkrupo** [comment]
> @tpalli @js0701 @harishkrupo :
> we have also notice stark differences in the GPU frequency residencies in the higher freq range (with OVERALLOC at 300 vs OVERALLOC at 100)

That might explain better scores, but what caused an increase in gpu freq?

**Comment by yugang** [comment]
also want to know how fb var impacts the i915.   if i915 is using the var from fb, can we find the place in i915 to change instead of going fb side?

**Comment by harishkrupo** [comment]
@yugang i915 doesn't use the var directly. The var is used in the drm framework to decide the height of the fb surface (for fb0 device/fbcon). This is only done at initialization or in response to a hotplug event.

**Comment by dyang23** [comment]
May I know how many extra memory will be used, will it impact the whole display system's memory usage?
If not too much, I am Ok with this patch.

**Comment by apnavik** [comment]
> May I know how many extra memory will be used, will it impact the whole display system's memory usage?
> If not too much, I am Ok with this patch.

It is 8MB increment from the carveout memory. It doesn't have any side effect in other system's memory.

**Comment by dyang23** [comment]
+1

**Comment by zhangn1985** [comment]
it's very BAD to change default kernel config. if you REALLY want this change, please add **drm.drm_fbdev_overalloc=300** to kernel cmdline.

**Comment by tpalli** [comment]
@apnavik did you guys test danvet's patch (http://paste.debian.net/1067552/), was there any effect with this?

**Comment by apnavik** [comment]
> @apnavik did you guys test danvet's patch (http://paste.debian.net/1067552/), was there any effect with this?

@tpalli : We have verified the test cases for long time duration suggested by danvet. We have not seen any side effect. 
We have also verified making fbdev to null with OVERALLOC=300 and observed no effect. we will be verifying with OVERALLOC=100 as well.

**Comment by tpalli** [comment]
@apnavik ok, thanks for testing that one!

**Comment by apnavik** [comment]
> > @apnavik did you guys test danvet's patch (http://paste.debian.net/1067552/), was there any effect with this?
> 
> @tpalli : We have verified the test cases for long time duration suggested by danvet. We have not seen any side effect.
> We have also verified making fbdev to null with OVERALLOC=300 and observed no effect. we will be verifying with OVERALLOC=100 as well.

@tpalli : We have observed no effect with danvet's patch + OVERALLOC=100

**Comment by vipinanand** [comment]
Raising new pull request for latest code.

**Pull request closed without merging**
