### PR TITLE
Summary: device type car mixin changes

### PR DESCRIPTION
**Pull request by anithax**
[MIXINUP] Fix for changing the order of overlay car makefile

Description:
- Changed the order of device type car in mixins.spec

Jira: https://jira01.devtools.intel.com/browse/OAM-67764

Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>

### CODE REVIEW

**Comment by android-ia-srv** [comment]
Commit message is verified for commit id:  https://github.com/projectceladon/device-androidia/pull/54/commits/85f87276b84d50915c79ceca5774f1e578e1b37a <br>

**Comment by anithax** [comment]
Request for review - Jeevaka.Badrappan@intel.com

**Comment by anithax** [comment]
@JeevakaPrabu

**Comment by android-ia-srv** [comment]
Commit message is verified for commit id:  https://github.com/projectceladon/device-androidia/pull/54/commits/116fed151e06966903230900caf440b709b2db76 <br>

**Comment by anithax** [comment]
Request to review @JeevakaPrabu

**Pull request merged**
