### PR TITLE
Enable GAS package for the CEL_KBL and CEL_APL

### PR DESCRIPTION
**Pull request by arvinwax**
Change-Id: I80d24777b9b9f7733c42c949d9170015dfbe4cdb
Tracked-On: OAM-76314
Signed-off-by: Yan, WalterX <walterx.yan@intel.com>

### CODE REVIEW

**Comment by hongcheng-xie** [comment]
For such GAS related bsp patch, since the google diff patch is still open source and easy to happen code conflict later, suggest to:
1) Remove diff patch and integrate the patch into projectceladon/device-androidia project directly;
Or 2) Integrate the diff patch into private embargoed google diff repo;

**Comment by arvinwax** [comment]
Verify +1

**Comment by hongcheng-xie** [comment]
@arvinwax, after all stakeholders agree this new solution, pls remove google diff patch first and submit patch for both kbl and apl target.

**Comment by arvinwax** [comment]
> @arvinwax, after all stakeholders agree this new solution, pls remove google diff patch first and submit patch for both kbl and apl target.

Got.

**Comment by arvinwax** [comment]
Verify +1
Remove diff patch PR:
https://github.com/projectceladon/vendor-intel-utils/pull/226

Hi @hongcheng-xie @walterx-yan 
Could you please help to review.
Thanks.

**Comment by arvinwax** [comment]
Hi @hongcheng-xie 
remove the vendor/google/gas/products/gas.mk
Build successfully.

**Pull request merged**
