### PR TITLE
Update mesa bsp diff

### PR DESCRIPTION
**Pull request by renchenglei**
We will upgrade mesa from 19.1.6 to 19.3.3, this change
helps to update mesa building diff and remove previous mesa
19.1.6 library.

Tracked-On: OAM-89814
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
@renchenglei Do you need all those DRI_CONF changes? Is there some documentation on why these changes are made, for some tests?

**Comment by renchenglei** [comment]
@tpalli, this is changed by AOSP team for CIC(Celadon in Container) project. And we have one round of mesa rebase requirement for CIC project. I just rebase the bsp diff to align with the new mesa version. 
For CIV(Celadon in Virtualization) and Tablet, we don't need this. This is for "celadon/p/mr0/cic" branch.

**Comment by renchenglei** [comment]
@sgnanase, could you help take a review of this changes? Thanks a lot!

**Comment by renchenglei** [comment]
We have finished pre-integration test, and need @sgnanase's approval flag to merge, :)

**Comment by renchenglei** [comment]
Close this as Sundar has updated the bsp file path.
https://github.com/projectceladon/vendor-intel-utils/pull/605

**Pull request closed without merging**
