### PR TITLE
set_storage: set sepolicy after enable treble.

### PR DESCRIPTION
**Pull request by tanminger**
Tracked-On: OAM-74945
Signed-off-by: Ming Tan <ming.tan@intel.com>

### CODE REVIEW

**Comment by tanminger** [comment]
If delete the "allow set_storage frp_block_device:blk_file setattr;"
It will show the following error:
[4200.030235 0.010750] [    8.632539] audit: type=1400 audit(1547003269.253:8): avc:  denied  { setattr } for  pid=2659 comm="set_storage.ven" name="nvme0n1p9" dev="tmpfs" ino=12463 scontext=u:r:set_storage:s0 tcontext=u:object_r:frp_block_device:s0 tclass=blk_file permissive=0

**Comment by tanminger** [comment]
But even it show the error, but the owner of nvme0n1p9 still changed to system.

**Comment by tanminger** [comment]
Updated, please review again.

**Comment by ceiba1985** [comment]
For [4200.030235 0.010750] [ 8.632539] audit: type=1400 audit(1547003269.253:8): avc: denied { setattr } for pid=2659 comm="set_storage.ven" name="nvme0n1p9" dev="tmpfs" ino=12463 scontext=u:r:set_storage:s0 tcontext=u:object_r:frp_block_device:s0 tclass=blk_file permissive=0

if this error wouldn't cause any regression, you can add "dontaudit set_storage frp_block_device:blk_file setattr;" to set_storage.te to eliminate this error log

**Comment by ceiba1985** [comment]
I think you'd better let ueventd change the attribute of a device, you can define the basic rule in ueventd.rc.

**Pull request merged**
